### ISSUE TITLE
`bibretrieve-base.el` should require `bibretrieve.el`

### ISSUE THREAD

**Issue by astoff** [pzorin/bibretrieve#7]
Otherwise, one gets an error message saying `bibretrieve-backends` is not defined when calling `bibretrieve` without first loading the `bibretrieve` library.

**Comment by astoff** [comment]
Or, preferably, the contents of `bibretrieve-base.el` should be moved to `bibretrieve.el`. If the package is installed from MELPA (or manually with `package-install-file`), it is not necessary to add `(require 'bibretrieve)` in the init file anyway.

By the way, it would be nice to release this on https://stable.melpa.org/

**Comment by pzorin** [comment]
I have implemented an alternative solution in da7b8c4
