### ISSUE TITLE
bibretrive sometimes fails

### ISSUE THREAD

**Issue by ouboub** [pzorin/bibretrieve#9]
Hi

I am using version 20170906.1036 as found in the emacs package system, with Ubuntu 14.04 and emacs 26

However some entries bibretrive seems to be unable to find, take this for example

@article {MR1076448,
    AUTHOR = {Chemin, J.-Y.},
     TITLE = {Dynamique des gaz \`a masse totale finie}, 
   JOURNAL = {Asymptotic Anal.},
  FJOURNAL = {Asymptotic Analysis},
    VOLUME = {3},
      YEAR = {1990},
    NUMBER = {3},
     PAGES = {215--220},
      ISSN = {0921-7134},
   MRCLASS = {76N15 (35Q99)},
  MRNUMBER = {1076448},
MRREVIEWER = {Andrzej Palczewski},
}

I searched for the author Chemin, J.-Y.
and the title as indicated. I also tried to translate the 7-bit string of the title to UTF-8, it did not work either.  Not sure who is the culprit here.

regards

Uwe Brauer

**Comment by pzorin** [comment]
In this case the problem is the author name: searching for author "Chemin" and title as indicated works. I am not sure how to specify author first name in mathscinet queries.

**Comment by ouboub** [comment]
ah, you are right, thanks
